# name: Build
# on: push

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         profile: [development, preview, production]

#     steps:
#       - uses: actions/checkout@v4

#       - uses: actions/setup-node@v4
#         with:
#           node-version: 24

#       - run: npm install

#       - uses: PlatanoLabs/eas-build-action@v0.1.0
#         id: build
#         with:
#           expo-token: ${{ secrets.EXPO_TOKEN }}
#           platform: android
#           profile: ${{ matrix.profile }}

#       - uses: actions/upload-artifact@v4
#         with:
#           name: android-build-${{ matrix.profile }}
#           path: ${{ steps.build.outputs.build-path }}
name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Build app
        run: eas build --local --non-interactive --platform android --profile preview

      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: assets-for-download
          path: build-*.apk
