name: Build
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install

      - uses: PlatanoLabs/eas-build-action@v0.1.0
        id: build
        with:
          expo-token: ${{ secrets.EXPO_TOKEN }}
          platform: android
          profile: production

      - uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: ${{ steps.build.outputs.build-path }}
